### ISSUE TITLE
Modelo de negócio - Público Alvo?

### ISSUE THREAD

**Issue by Gabriel-Alves02** [Gabriel-Alves02/MatchSquad#1]

**Comment by ALManriqueJR** [comment]
Público Alvo

Abaixo das grandes corporações, a aplicação enxerga toda fatia de mercado de pessoas jurídicas como público em potencial (MEI e MPE), como também, ainda considerando a incubação de ideias que precisam de um “empurrão” inicial, considerando-se o público geral de pessoas físicas como possiveis interessados no financiamento de ideias.
E dado ainda as possibilidades de nichos que podem ser implementados de acordo com cada ideia, os beneficiados podem ser dos mais variados públicos, independente de classe social, etnia, religião, localização, etc.
