### ISSUE TITLE
Nível de Dificuldade do Sistema Proposto || Quantidade de Dores (Casos de Uso). Atenção  Cadastros e Login não são dores dos usuários. Quais Dores?

### ISSUE THREAD

**Issue by ALManriqueJR** [Gabriel-Alves02/MatchSquad#10]

**Comment by Gabriel-Alves02** [comment]
As dores/casos de uso dos clientes da MatchSquad são:

1) Procurar/encontrar mentor;
2) Analisar perfil do mentor (por parte do empreendedor);
3) Analisar perfil do empreendedor (por parte do mentor, para direcionar melhor sua mentoria);
4) Assistir/ministrar uma mentoria à distância;
5) Melhorar seu trabalho (mentoria) através da avaliação do cliente.
