### ISSUE TITLE
Nível de Dificuldade do Sistema Proposto || Quantidade de Telas: Quais telas?

### ISSUE THREAD

**Issue by ALManriqueJR** [Gabriel-Alves02/MatchSquad#12]

**Comment by Gabriel-Alves02** [comment]
A aplicação terá 11 telas principais e outras telas informativas. São elas:

1)   Tela de pesquisa de mentores;
2)   Tela de perfil do mentor;
3)   Tela de perfil do empreendedor;
4)   Tela de avaliação da mentoria;
5)   Tela de agendamento de mentoria;
6)   Tela de videochamada para realização da mentoria;
7)   Tela de consulta de mentorias agendadas;
8)   Tela de consulta de relatórios de Avaliação;
9)   Tela de consulta de relatório de Histórico de Match;
10) Tela de consulta de Relatório de Progressão;
11) Tela de Contrato de Mentoria;
12) Telas informativas.
