### ISSUE TITLE
Tecnologia Utilizadas "FrontEnd"

### ISSUE THREAD

**Issue by ALManriqueJR** [Gabriel-Alves02/MatchSquad#13]

**Comment by Gabriel-Alves02** [comment]
Serão utilizadas as seguintes tecnologias para a etapa de desenvolvimento FrontEnd:

1)	HTML e CSS;
2)	JavaScript;
3)	Headroom.js;
4)	React;
5)	VSCode;
6)	GitHub;
7)	Git cliente.
