### ISSUE TITLE
Casos de uso - Mentor

### ISSUE THREAD

**Issue by Gabriel-Alves02** [Gabriel-Alves02/MatchSquad#17]

**Comment by ALManriqueJR** [comment]
![Image](https://github.com/Gabriel-Alves02/MatchSquad/assets/5949045/3b1441a7-c61d-4e6e-9c80-5874e205a11a)

**Comment by ALManriqueJR** [comment]
NEW

![Image](https://github.com/Gabriel-Alves02/MatchSquad/assets/5949045/098366ce-6ea6-4690-bdb9-d96631ee8c13)
