### ISSUE TITLE
Definir documentação da mentoria

### ISSUE THREAD

**Issue by Gabriel-Alves02** [Gabriel-Alves02/MatchSquad#24]

**Comment by ALManriqueJR** [comment]
CONTRATO DE PRESTAÇÃO DE SERVIÇOS EDUCACIONAIS

IDENTIFICAÇÃO DAS PARTES CONTRATANTES

MENTOR: [Nome do Contratante] - [Profissão] – [Especialidade]
Carteira de Identidade nº [xxx], C.P. F. nº [xxx]
Logradouro (Residencia ou Escritório) : Rua [xxx], nº [xxx], bairro [xxx], Cep [xxx], Cidade [xxx] - Estado [xxx];

EMPRESA: [Nome da Fantasia], inscrita no C.N.P.J. sob o nº [xxx], e no Cadastro Estadual sob o nº [xxx].
Logradouro : Rua [xxx], nº [xxx], bairro [xxx], Cep [xxx], Cidade [xxx] - Estado [xxx], neste ato representada pelo seu diretor [xxx], Carteira de Identidade nº [xxx], C.P. F. nº [xxx].

As partes acima identificadas têm, entre si, justo e acertado o presente Contrato de Prestação de Serviços Educacionais, que se regerá pelas cláusulas seguintes e pelas condições de preço, forma e termo de pagamento descritas no presente.

DO OBJETO DO CONTRATO

Cláusula 1ª. O presente contrato tem como OBJETO, a prestação, pelo MENTOR, de serviços educacionais, a serem realizados de forma online na plataforma MatchSquad, ou em encontro presencial em data e local combinado entre as partes..

DA OBRIGAÇÂO DO MENTOR

Cláusula 2ª. Orientar e estabelecer planejamento incremental aos assuntos tratados em mentorias, prestando auxílios as dúvidas, durante o vigor do contrato.
Cláusula 3ª. Preencher o relatório de registro das atividades trabalhadas durante a mentoria, para documentar e conferir rastreabilidade do acompanhamento de maneira formalizada.

Cláusula 4ª.Todos conteúdos devem ser submetidos previamente para analisa da plataforma, para que seja feito a análise de conformidade de qualidade, o conteúdo e como ele é exposto.

AOS DESCONTOS

Cláusula 5ª. O MENTOR goza do direto intelectual de seu material integramente, todavia, em plataforma o conteúdo está atrelado aos planos. Dessa forma, tem-se o comprometimento em estabelecer preços competitivos ao mercado, de acordo com cada plano. A angariação de público pela plataforma, para venda em preço menor que o combinado, é passível de desativação da conta do MENTOR após a apuração dos casos.

DO PAGAMENTO

Cláusula 6ª. Em virtude da prestação dos serviços educacionais, a MatchSquad pagará ao MENTOR a quantia em função do cálculo do plano e após mentoria em ciclo mensal.

Cláusula 7ª. Da dispensa da empresa sobre a prestação do serviços, por quaisquer circunstâncias, os meses restantes ao plano serão divididos meio a meio entre a MatchSquad e o MENTOR.

DA RESCISÃO

Cláusula 7ª. O presente instrumento poderá ser rescindido por qualquer das partes, com necessidade de aviso prévio, de 3 dias úteis.

Cláusula 8ª. Será avaliado de maneira proporcional o tempo de contrato como também quantidade de mentoria ministradas para cálculos de pagamento.

Cláusula 9ª. Em ocorrendo a rescisão, o MENTOR é obrigado em fornecer um compilado de assuntos trabalhados, para que um novo mentor possa assumir dando seguimento do que já foi abordado.

DO PRAZO

Cláusula 10ª. O presente contrato terá duração de [xxx], iniciando-se no dia [xxx], e terminando no dia [xxx].

CONDIÇÕES GERAIS

Cláusula 11ª. A validade deste instrumento está condicionada à data de match, até o término do contrato referente ao plano escolhido.

Cláusula 12ª. A não frequência da empresa não impacta no pagamento, mas deve ser postada no relatório dos respectivos indicadores de progressão.

Cláusula 13ª. O MENTOR não se obriga a fornecer qualquer tipo de material didático, mas orientar as melhores fontes para consulta de determinados assuntos trabalhados.

DO FORO

Cláusula 17ª. Para dirimir quaisquer controvérsias oriundas do CONTRATO, as partes elegem o foro da comarca de [xxx];

Por estarem assim justos e contratados, firmam o presente instrumento, em duas vias de igual teor, juntamente com 2 [duas] testemunhas.

[Local, Data e ano].

[Nome e assinatura do Contratante]

[Nome e assinatura do Representante legal da Contratada]

[Nome, RG e assinatura da Testemunha 1]

[Nome, RG e assinatura da Testemunha 2]

________

Nota:
1. Art. 1º, do Decreto nº 22.626/33.
