### ISSUE TITLE
Protótipo (HTML e CSS)

### ISSUE THREAD

**Issue by Gabriel-Alves02** [Gabriel-Alves02/MatchSquad#30]

**Comment by ALManriqueJR** [comment]
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Matchsquad</title>
    <link rel="icon" href="assets/Icon.png  " type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="style.css">

</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <img class="navbar-brand" src="assets/Logo.png"></img>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link" href="Pre-login/FAQ.html">Como Funciona? </a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Planos
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Bronze</a></li>
                      <li><a class="dropdown-item" href="#">Prata</a></li>
                      <li><a class="dropdown-item" href="#">Ouro</a></li>
                    </ul>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="Pre-login/CadastroCC.html">Seja um Coach | Consultor</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="Pre-login/Login.html">Login</a>
                </li>
            </ul>
        </div>
    </nav>
    <br>

    <div class="container mt-1">
        <p class="cx_Top-Right">Novo na Matchsquad?<br> <a href="Pre-login/CadastroCliente.html"><button class="btn btn-outline-success"  style="margin-right: 25px;" type="submit">Cadastre-se</button></a></p>
    </div>

    
    <div class="container mt-5">
        <h1 class="text-primary">Bem-vindo a Matchsquad!</h1>
        <p style="text-align: right;">🧩Já são 1.000.000 matches!🧩</p>
        <p class="lead">Esta procurando como deslanchar seu negócio?...<br><p style="text-align: center;" class="lead">Encontrou! Os melhores profissionais se encontram aqui ;)</p></p>

        <section>  
            <div>
                <input type="checkbox" checked />
                <label>Coach</label=>
                <input type="checkbox" checked/>
                <label>Consultor</label>
            </div>

            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Qual o seu interesse?" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">🔎</button>
            </form>
        </section>
        
        
        
        <div class="row">

            <div class="col-md-4">
                
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                        <a  href="Pre-login/Portifolio.html"><img class="img-box" src= "../assets/1.jpg"></img></a>
                        <br><br>
                        <h5 class="card-title">Gisele Tabata Fikadika</h5>
                        <p class="card-text">Prestigiada como melhor empreendora do milenio.</p>
                    </div>
                </div>

            </div>

            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                        <img src="assets/2.jpg" class="img-box" alt="">
                        <br><br>
                        <h5 class="card-title">Dave, The Magical Cheese Wizard</h5>
                        <p class="card-text">Especialista em <i>pspspspspsps</i>. Campeao de brigas em telhados</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                        <img src="assets/8.jpg" class="img-box" alt="">
                        <br><br>
                        <h5 class="card-title">Aroldo Marcel Otto</h5>
                        <p class="card-text">Experiencia em trade de bitcoins e sites de apostas</p>
                    </div>
                </div>
            </div>


            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                        <img src="assets/6.jpg" class="img-box" alt="">
                        <br><br>
                        <h5 class="card-title"> Misato Hanabi</h5>
                        <p class="card-text">Programadora fullstack, criadora do primeiro voo tripulado ao Sol</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                        <img src="assets/4.jpg" class="img-box" alt="">
                        <br><br>
                        <h5 class="card-title">Jorge</h5>
                        <p class="card-text"> Boa companhia para churrasco. Ganhou Nobel da Paz</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                        <img src="assets/5.jpg" class="img-box" alt="">
                        <br><br>
                        <h5 class="card-title">Carlos Readr Acrobbat</h5>
                        <p class="card-text">Analista de livros best-seller, mantenedor do blog MelhorLeitura.</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                        <img src="assets/7.jpg" class="img-box" alt="">
                        <br><br>
                        <h5 class="card-title">Adalberto Dicaspio</h5>
                        <p class="card-text">Alavanca vendas em famosa empresa de bebidas gaseificadas</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                        <img src="assets/3.jpg" class="img-box" alt="">
                        <br><br>
                        <h5 class="card-title">Cesar Monke</h5>
                        <p class="card-text">Social, Trabalho em Equipe, Proativo. Atuou com Jack Sparrow</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                        <img src="assets/9.jpg" class="img-box" alt="">
                        <br><br>
                        <h5 class="card-title">Natid Abudab</h5>
                        <p class="card-text"> Criador dos numeros indo-arabicos. Especialista em economica petrolifera</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <h2 class="lead" style="text-align: center;"> ↓</h2>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

<footer style="background-color: #cbe2f8;">
    <div class="container-fluid text-center margin">
        <div class="row">
            <div class="col-lg-4">

                <br>
                <a href="" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Politicas de Privacidade
                </a>
                <br> <br>
                <a href="" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Termos de Uso
                </a=>
                <br> <br>
                <a href="" data-bs-target="#exampleModal2" data-bs-toggle="modal">
                    Ajuda
                </a>
                <br>
                  
                  
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Leia com atenção</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                    <p style="text-align: justify; text-justify: inter-word;">
                                        CONTRATO DE PRESTAÇÃO DE SERVIÇOS EDUCACIONAIS

                                            IDENTIFICAÇÃO DAS PARTES CONTRATANTES <br><br>

                                            MENTOR: [Nome do Contratante] - [Profissão] – [Especialidade]<br>
                                            Carteira de Identidade nº [xxx], C.P. F. nº [xxx]<br>
                                            Logradouro (Residencia ou Escritório) : Rua [xxx], nº [xxx], bairro [xxx], Cep [xxx], Cidade [xxx] - Estado [xxx];<br><br>
                                            <br>
                                            EMPRESA: [Nome da Fantasia], inscrita no C.N.P.J. sob o nº [xxx], e no Cadastro Estadual sob o nº [xxx].
                                            Logradouro : Rua [xxx], nº [xxx], bairro [xxx], Cep [xxx], Cidade [xxx] - Estado [xxx], neste ato representada pelo seu diretor [xxx], Carteira de Identidade nº [xxx], C.P. F. nº [xxx].<br>
                                            <br><br>
                                            As partes acima identificadas têm, entre si, justo e acertado o presente Contrato de Prestação de Serviços Educacionais, que se regerá pelas cláusulas seguintes e pelas condições de preço, forma e termo de pagamento descritas no presente.<br>
                                            <br><br>
                                            DO OBJETO DO CONTRATO<br>
                                            <br><br>
                                            Cláusula 1ª. O presente contrato tem como OBJETO, a prestação, pelo MENTOR, de serviços educacionais, a serem realizados de forma online na plataforma MatchSquad, ou em encontro presencial em data e local combinado entre as partes..<br>
                                            <br><br>
                                            DA OBRIGAÇÂO DO MENTOR<br>
                                            <br><br>
                                            Cláusula 2ª. Orientar e estabelecer planejamento incremental aos assuntos tratados em mentorias, prestando auxílios as dúvidas, durante o vigor do contrato.<br>

                                            .
                                            .
                                            .
                                    </p>
                            </div>
                            <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                            </div>
                    </div>
                    </div>
                </div>

                <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                   <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Contato nosso representante:</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                                <div class="modal-body">
                                        <p style="text-align: justify; text-justify: inter-word;">
                                            <p class="lead"> Como posso lhe ajudar?</p>
                                            📱  (15) 99150-1628
                                            <br>
                                            📧 billportoes@matchsquad.com.br
                                            <br><textarea name="" id=""></textarea><br>
                                            <button class="btn btn-outline-success" type="submit">➤</button>   
                                        </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                

            <div class="col-lg-4">
                <br>
                <h4>Contato</h4>
                <p>
                    (15) 99170-7070 📱
                </p>
                <br>
                <h4>Endereço</h4>
                <a target="_blank"
                    href="https://www.google.com/maps/@-23.4826573,-47.4260076,3a,75y,8.66h,90.1t/data=!3m6!1e1!3m4!1s0jnFsJazevJtZaqBOyuL5Q!2e0!7i13312!8i6656?entry=ttu">Av.
                    Engenheiro Carlos Reinaldo Mendes, 2015<br>Alto da Boa Vista - Sorocaba/SP</a>
                    <br><br>
            </div>

            <div class="col-lg-4" style="align-items: center;">
                <br>

                <table>
                    <tr>
                        <th>⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀</th>
                        <th style="text-align: center;"> <a href="https://www.facebook.com/fatecsorocaba/?locale=pt_BR" class="fa fa-facebook" target="_blank"></a></th>
                        <th>⠀</th>
                        <th style="text-align: center;"><a href="https://www.instagram.com/fatecsorocaba/?hl=en" class="fa fa-instagram" target="_blank"></a></a></th>
                        <th>⠀</th>
                        <th style="text-align: center;"><a href="https://www.linkedin.com/groups/2283743/" class="fa fa-linkedin" target="_blank"></a></th>
                        <th>⠀</th>
                        <th style="text-align: center;"><a href="" class="fa fa-twitter" target="_blank"></a></th>
                        <th>⠀</th>
                        <th style="text-align: center;"> <a href="https://www.facebook.com/fatecsorocaba/?locale=pt_BR" class="fa fa-tumblr" target="_blank"></a></th>
                        <th>⠀</th>
                    </tr>
                </table>

                <br><br>
                <p><atarget="_blank" href="https://github.com/Gabriel-Alves02/MatchSquad">Matchsquad</atarget=> 2024 - Fatec (Sorocaba/Sao Paulo)</p>
                <br>
            </div>
        </div>
    </div>
</footer>
</html>

**Comment by ALManriqueJR** [comment]
body {
    background-color: #ffffff;
    color: #000000;
}

:root {
    --blue: #1573E5;
}

h1{
    -webkit-text-stroke: 0.8px black;
}

.btn-outline-success {
    --bs-btn-color: #1573E5;
    --bs-btn-border-color: #1573E5;
    --bs-btn-hover-color: #fff;
    --bs-btn-hover-bg: #1573E5;
    --bs-btn-hover-border-color: #1573E5;
    --bs-btn-focus-shadow-rgb: 25, 135, 84;
    --bs-btn-active-color: #fff;
    --bs-btn-active-bg: #1573E5;
    --bs-btn-active-border-color: #1573E5;
    --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
    --bs-btn-disabled-color: #1573E5;
    --bs-btn-disabled-bg: none;
    --bs-btn-disabled-border-color: #1573E5;
    --bs-gradient: none;
}

.btn {
    color: #d2d7df;
    background-color: #1573E5;
}

.navbar-light{
    color: #007bff;
}

.card {
    border: 1px solid #1573E5;
}

.navbar navbar-expand-lg navbar-light bg-light{
    border: #1573E5;
}

.d-flex{
    margin-bottom: 50px;
    margin-top: 10px;
}

.lead{
    margin-top: 20px;
}

.navbar-brand{
    min-height: 5px;
    min-width: 10px;
    max-height: 180px;
    max-width: 250px;
    padding-left: 10px;
}

.cx_Top-Right{
    text-align: right;
    margin-right: 35px;
    margin-bottom: 0px;
    padding-bottom: 0px;
    border-bottom: 0px;
}

.text-primary{
    margin-bottom: 50px;
    text-align: center;
    color: #1573E5;

}

.img-box{
    width: 12rem;
    height: 12rem;
    border-radius: 50%;
    margin-left: 20%;
}

a:link { 
  text-decoration: none; 
} 
a:visited { 
  text-decoration: none; 
} 
a:hover { 
  text-decoration: none; 
} 
a:active { 
  text-decoration: none; 
}

#customerForm{
    padding: 20px 10px 5px 2px;
}

.formfill{
    width: 230px;
    height: 40px;
}


#bodyCad{
    background-image: url(assets/CadWpp.jpg);
    background-repeat: no-repeat;
    background-size: cover;
}

#bodyCC{
    background-image: url(assets/LogWpp2.jpg);
    background-repeat: no-repeat;
    background-size: cover;
}

.profile {
    display: flex;
    align-items: center;
    margin: 20px 0;
    background-image: url(../assets/Banner.jpg);
    background-repeat: no-repeat;
    background-size: cover;
}

.bio {
    flex: 1;
}

.bio h2 {
    margin: 0 0 10px;
}

.profile-photo {
    border-radius: 50%;
    width: 180px;
    height: 180px;
    padding: 0.5%;
}

.certif{
    width: 60%;
    height: 40%;
    margin-left: 4.9rem;
}

.imgEmp{
    width: 10rem;
    height: 8rem;
}
