### ISSUE TITLE
Código PlantUML - MatchSquad

### ISSUE THREAD

**Issue by Gabriel-Alves02** [Gabriel-Alves02/MatchSquad#31]

**Comment by aranhasd** [comment]
@startuml "use-cases"
left to right direction
actor MatchSquad as M
package MatchSquad {
usecase "Comunicar Clientes" as UC1
usecase "Recebe Avaliação" as UC2
usecase "Repassar Avaliação" as UC3
usecase "Administrar Preços de Planos" as UC4
usecase "Verificar pagamentos" as UC5
usecase "Administrar Mentores" as UC6
usecase "Administrar Planos" as UC7
usecase "Bloquear Mentor" as UC8
}
M --> UC1
M --> UC6
M --> UC5
M --> UC2
M --> UC3
M --> UC4
M --> UC7
M --> UC8

(UC2) .up.> (UC3) : <<includes>>
(UC6) .up.> (UC8) : <<includes>>

@enduml

**Comment by ALManriqueJR** [comment]
Atualizado e disposto no READ.me
