### ISSUE TITLE
Código PlantUML - Empreendedor

### ISSUE THREAD

**Issue by Gabriel-Alves02** [Gabriel-Alves02/MatchSquad#32]

**Comment by Gabriel-Alves02** [comment]
@startuml "use-cases"
left to right direction
actor Empreendedor as E
package MatchSquad {
    usecase "Comprar Plano" as UC1
    usecase "Agendar Mentoria" as UC2
    usecase "Assistir Mentoria" as UC3
    usecase "Avaliar Mentoria" as UC4
    usecase "Assistir Triagem" as UC5
    usecase "Agendar Triagem" as UC6
    usecase "Cancelar Agendamento" as UC7
}
E --> UC1
E --> UC6
E --> UC5
E --> UC2
E --> UC3
E --> UC4
E --> UC7

(UC2) .up.> (UC5) <<includes>>
(UC4) .up.> (UC3) <<includes>>


@enduml

**Comment by Gabriel-Alves02** [comment]
![Image](https://github.com/Gabriel-Alves02/MatchSquad/assets/161254104/9c8a1c3a-353d-43d7-b40d-8dc9e197ca0c)

**Comment by ALManriqueJR** [comment]
Atualizado e disposto no READ.me
