### ISSUE TITLE
Telas Consultores (Figma)

### ISSUE THREAD

**Issue by Gabriel-Alves02** [Gabriel-Alves02/MatchSquad#35]

**Comment by ALManriqueJR** [comment]
![Image](https://github.com/Gabriel-Alves02/MatchSquad/assets/5949045/e0e0e337-2784-46f6-9fb2-882020fb5fa1)

**Comment by ALManriqueJR** [comment]
Menu Mentor

- Mail
- Agenda
- Contratos

(Historico e Relatorios são emitidos com base nas telas, em pdf contiguo por exemplo)

**Comment by ALManriqueJR** [comment]
![Image](https://github.com/Gabriel-Alves02/MatchSquad/assets/5949045/1bf07ae1-430b-4905-a616-e5b777cc54f9)

**Comment by ALManriqueJR** [comment]
https://www.figma.com/file/duECfgkcSOjXFHZnNDrTCz/MatchSquad?type=design&node-id=0-1&mode=design&t=fnleuvuIGgfVYZN3-0
