### ISSUE TITLE
Modelo de negócio - Formas de Monetização?

### ISSUE THREAD

**Issue by ALManriqueJR** [Gabriel-Alves02/MatchSquad#5]

**Comment by Gabriel-Alves02** [comment]
A monetização pode ser feita por meio de planos mensais com acesso à uma determinada quantidade de mentorias por mês ou por venda avulsa de mentorias, neste caso o mentor precifica sua mentoria e vende pela plataforma que cobra comissão para venda e uso das ferramentas da plataforma.
