### ISSUE TITLE
Modelo de negócio - Concorrentes?

### ISSUE THREAD

**Issue by ALManriqueJR** [Gabriel-Alves02/MatchSquad#7]

**Comment by Nats456** [comment]
Sebrae - A Mentoria para Startups é um momento de 60 minutos com nossos mentores especializados em diferentes áreas de gestão de negócios inovadores. Trata-se de uma oportunidade de desenvolver sua ideia de negócio ou avançar o grau de maturidade de sua Startup.  
Por meio da mentoria você vai melhorar a capacidade de gerir sua autoaprendizagem, será capaz de compreender melhor o mercado em que está inserido, vai amadurecer suas ideias de modelos de negócios e melhorar seu desempenho em busca de resultados de forma ágil e segura. 

 

Abstartup - A Abstartups oferece um programa de mentorias individuais em diversas categorias para auxiliar o desenvolvimento das startups. São bate-papos de uma hora com especialistas nos mais diversos temas. É sua oportunidade de apresentar sua startup e os desafios que está enfrentando para receber dicas e orientações. 

 

Guru de negócios - A mentoria é um dos pilares de apoio da Aliança Empreendedora e foi desenvolvida para oferecer um suporte personalizado aos empreendedores no desenvolvimento de habilidades para empreender e para auxiliá-los a identificar oportunidades durante a abertura e o crescimento dos seus negócios através da troca de experiências. 
Acreditamos que o empreendedor acompanhado por um mentor tem maiores chances de sucesso. Assim, através da mentoria, buscamos que o empreendedor se sinta mais empoderado, aumente sua renda e, consequentemente, fortaleça seu negócio e torne-o mais sustentável. 
Para a mentoria acontecer, empreendedores são conectados a mentores voluntários, responsáveis pelo acompanhamento individualizado com cada empreendedor. 

 

Programa Scale-Up Endeavor É uma iniciativa que visa impulsionar o crescimento do ecossistema de negócios no Brasil, oferecendo uma jornada personalizada de conexões e mentorias para empresas com alto potencial de crescimento. O programa seleciona duas vezes ao ano um grupo de empresas e, ao longo de cinco meses, oferece encontros coletivos e individuais, conexões com mentores especializados no modelo ou setor de negócio de cada empresa, além de celebrar os avanços ao final do período de aceleração. O programa é totalmente equity free, ou seja, não requer participação acionária das startups participantes. No entanto, há uma contribuição mensal de R$6 mil ao longo dos cinco meses para viabilizar a operação do programa, e são oferecidas parcerias para créditos exclusivos em plataformas de hospedagem em nuvem e CRM, proporcionando um retorno financeiro significativo para as empresas apoiadas. Esta contribuição mensal também garante o engajamento dos empreendedores ao longo do programa, facilitando trocas de alto nível entre os participantes.

**Comment by ALManriqueJR** [comment]
Verificado que apos aprumar modelos de negocio, concorrentes diretos seria a SEBRAE, e ate mesmo Anjos Brasil
