### ISSUE TITLE
Nível de Dificuldade do Sistema Proposto || Quantidade de Tabelas, quais tabelas?

### ISSUE THREAD

**Issue by ALManriqueJR** [Gabriel-Alves02/MatchSquad#9]

**Comment by Gabriel-Alves02** [comment]
A aplicação terá 5 tabelas. São elas:

1)	Tabela de mentores;
2)	Tabela de empreendedores;
3)	Tabela de mentores para empreendedores;
4)	Tabela de mentorias;
5)	Tabela de avaliações.
